title: "Force Map: Learning to Predict Contact Force Distribution from Vision"
author: Ryo Hanai<sup>1</sup>, Yukiyasu Domae<sup>1</sup>, Ixchel G. Ramirez-Alpizar<sup>1</sup>, Bruno Leme<sup>1</sup> and Tetsuya Ogata<sup>1,2</sup>
affiliation: <sup>1</sup>AIST, <sup>2</sup>Waseda University
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
paper: https://arxiv.org/abs/2304.05803v1
show_git_project: false
